apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cache
  name: cache
spec:
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - env:
        - name: UPSTREAM_SERVER
          value: https://example.com
        - name: ETCD
          value: http://etcd:2379
        image: fkautz/casserole:dev
        name: cache
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always

