apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: cache
  name: cache
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cache
    spec:
      containers:
      - env:
        - name: UPSTREAM_SERVER
          value: https://example.com
        - name: ETCD
          value: http://etcd:2379
        image: theterabyte/casserole:latest
        name: cache
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always

